name: Build Debug APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Create Android debug keystore
        run: |
          mkdir -p ~/.android
          keytool -genkeypair \
            -v \
            -keystore ~/.android/debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"
          ls -la ~/.android

      - name: Build debug APK
        run: ./gradlew assembleFossDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MetroList-landscape-debug-apk
          path: app/build/outputs/apk/foss/debug/*.apk
